// =====================================================================
// KKDGMS — Student Online Examination Portal (OTP, Timer, Autosave)
// =====================================================================

import React, { useState, useEffect } from 'react';
import {
  MonitorPlay,
  KeyRound,
  Clock,
  CheckCircle2,
  AlertTriangle,
  Send,
  HelpCircle,
  Award,
  Lock,
  Save,
  ShieldAlert
} from 'lucide-react';
import { OnlineExam, OnlineExamAttempt } from '../../types';
import { api } from '../../lib/supabase';

export const StudentOnlineExamPortal: React.FC = () => {
  const [exams, setExams] = useState<OnlineExam[]>([]);
  const [activeExam, setActiveExam] = useState<OnlineExam | null>(null);
  const [enteredStartOtp, setEnteredStartOtp] = useState('');
  const [examStarted, setExamStarted] = useState(false);
  const [secondsRemaining, setSecondsRemaining] = useState(0);

  // Student Draft Answers: question_id -> choice_id
  const [answers, setAnswers] = useState<Record<string, string>>({});
  const [currentQuestionIdx, setCurrentQuestionIdx] = useState(0);
  const [saveStatus, setSaveStatus] = useState<'saved' | 'saving' | 'offline'>('saved');

  // Submission & Result
  const [enteredEndOtp, setEnteredEndOtp] = useState('');
  const [showEndModal, setShowEndModal] = useState(false);
  const [examSubmitted, setExamSubmitted] = useState(false);
  const [resultAttempt, setResultAttempt] = useState<OnlineExamAttempt | null>(null);
  const [studentFeedback, setStudentFeedback] = useState('');

  useEffect(() => {
    loadExams();
  }, []);

  const loadExams = async () => {
    const list = await api.getOnlineExams();
    setExams(list);
  };

  // Timer countdown
  useEffect(() => {
    if (!examStarted || secondsRemaining <= 0 || examSubmitted) return;

    const timer = setInterval(() => {
      setSecondsRemaining((prev) => {
        if (prev <= 1) {
          clearInterval(timer);
          handleAutoSubmit();
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, [examStarted, secondsRemaining, examSubmitted]);

  const handleStartExam = (exam: OnlineExam) => {
    if (!enteredStartOtp.trim()) {
      alert('Please enter the 6-digit Start OTP provided by the invigilating faculty.');
      return;
    }

    // Verify OTP against exam.start_otp
    if (exam.start_otp && enteredStartOtp.trim() !== exam.start_otp) {
      alert('Invalid Start OTP. Please enter the current active OTP generated by your teacher.');
      return;
    }

    setActiveExam(exam);
    setExamStarted(true);
    setSecondsRemaining((exam.duration_minutes || 30) * 60);

    // Restore draft if any in localStorage
    const savedDraft = localStorage.getItem(`draft_${exam.id}`);
    if (savedDraft) {
      try {
        setAnswers(JSON.parse(savedDraft));
      } catch {}
    }
  };

  const handleSelectChoice = (questionId: string, choiceId: string) => {
    setSaveStatus('saving');
    const updated = { ...answers, [questionId]: choiceId };
    setAnswers(updated);

    // Automatic Draft Saving locally
    if (activeExam) {
      localStorage.setItem(`draft_${activeExam.id}`, JSON.stringify(updated));
    }

    setTimeout(() => {
      setSaveStatus('saved');
    }, 200);
  };

  const calculateScore = () => {
    if (!activeExam) return { score: 0, total: 0, percentage: 0, passed: false };
    let score = 0;
    activeExam.questions.forEach((q) => {
      if (answers[q.id] === q.correct_answer_id) {
        score += Number(q.marks) || 1;
      } else if (answers[q.id] && q.negative_marks) {
        score -= Number(q.negative_marks);
      }
    });

    const total = activeExam.total_marks || activeExam.questions.length * 5;
    const percentage = total > 0 ? Number(((score / total) * 100).toFixed(1)) : 0;
    const passed = score >= (activeExam.pass_marks || total * 0.4);

    return { score, total, percentage, passed };
  };

  const handleFinalSubmit = async () => {
    if (!activeExam) return;

    // Verify End OTP if required
    if (activeExam.end_otp && enteredEndOtp.trim() !== activeExam.end_otp) {
      alert('Invalid End OTP. Please request the finishing code from your teacher.');
      return;
    }

    const { score, total, percentage, passed } = calculateScore();

    const attempt = await api.submitExamAttempt({
      exam_id: activeExam.id,
      student_id: 's-001',
      student_name: 'A. Dhanush Kumar',
      student_user_id: 'EMIS202401',
      student_class: activeExam.student_class,
      section: activeExam.section,
      start_time: new Date().toISOString(),
      end_time: new Date().toISOString(),
      answers,
      score,
      total_marks: total,
      percentage,
      is_passed: passed,
      status: 'submitted',
      student_feedback: studentFeedback
    });

    // Cleanup draft
    localStorage.removeItem(`draft_${activeExam.id}`);

    setResultAttempt(attempt);
    setExamSubmitted(true);
    setShowEndModal(false);
  };

  const handleAutoSubmit = async () => {
    if (!activeExam || examSubmitted) return;
    const { score, total, percentage, passed } = calculateScore();

    const attempt = await api.submitExamAttempt({
      exam_id: activeExam.id,
      student_id: 's-001',
      student_name: 'A. Dhanush Kumar',
      student_user_id: 'EMIS202401',
      student_class: activeExam.student_class,
      section: activeExam.section,
      start_time: new Date().toISOString(),
      end_time: new Date().toISOString(),
      answers,
      score,
      total_marks: total,
      percentage,
      is_passed: passed,
      status: 'timed-out'
    });

    setResultAttempt(attempt);
    setExamSubmitted(true);
  };

  const formatTimer = (sec: number) => {
    const m = Math.floor(sec / 60);
    const s = sec % 60;
    return `${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}`;
  };

  // 1. Result View
  if (examSubmitted && resultAttempt) {
    return (
      <div className="max-w-2xl mx-auto bg-white rounded-3xl border border-slate-200 p-8 text-center space-y-6 shadow-sm animate-in zoom-in-95">
        <div className="w-16 h-16 rounded-full bg-emerald-50 text-emerald-600 flex items-center justify-center mx-auto">
          <Award className="w-8 h-8" />
        </div>

        <div>
          <h2 className="text-2xl font-black text-slate-900">Exam Successfully Evaluated</h2>
          <p className="text-xs text-slate-500 mt-1">{activeExam?.exam_name}</p>
        </div>

        <div className="grid grid-cols-3 gap-3 p-4 bg-slate-50 rounded-2xl border border-slate-100 font-mono">
          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase block">Your Score</span>
            <span className="text-xl font-black text-indigo-700">{resultAttempt.score} / {resultAttempt.total_marks}</span>
          </div>
          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase block">Percentage</span>
            <span className="text-xl font-black text-slate-800">{resultAttempt.percentage}%</span>
          </div>
          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase block">Outcome</span>
            <span className={`text-xl font-black ${resultAttempt.is_passed ? 'text-emerald-600' : 'text-rose-600'}`}>
              {resultAttempt.is_passed ? 'PASSED' : 'NEEDS REVISION'}
            </span>
          </div>
        </div>

        <div className="text-left space-y-2">
          <label className="text-xs font-bold text-slate-700">Exam Feedback / Remarks for Teacher</label>
          <textarea
            value={studentFeedback}
            onChange={(e) => setStudentFeedback(e.target.value)}
            placeholder="Share your comments or questions about specific test items..."
            className="w-full p-3 text-xs bg-slate-50 border border-slate-200 rounded-xl"
            rows={2}
          ></textarea>
        </div>

        <button
          onClick={() => {
            setExamSubmitted(false);
            setExamStarted(false);
            setActiveExam(null);
          }}
          className="w-full bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs uppercase py-3.5 rounded-xl transition-all shadow-md"
        >
          Return to Student Dashboard
        </button>
      </div>
    );
  }

  // 2. Active Exam Question Screen
  if (examStarted && activeExam) {
    const currentQ = activeExam.questions[currentQuestionIdx];
    const answeredCount = Object.keys(answers).length;

    return (
      <div className="max-w-4xl mx-auto space-y-6">
        {/* Timer Bar & Autosave Status */}
        <div className="bg-white p-4 rounded-2xl border border-slate-200 flex items-center justify-between shadow-xs sticky top-4 z-20">
          <div>
            <h3 className="text-sm font-bold text-slate-900">{activeExam.exam_name}</h3>
            <div className="flex items-center gap-2 mt-0.5 text-xs text-slate-500">
              <span className="flex items-center gap-1">
                <Save className="w-3.5 h-3.5 text-emerald-600" />
                {saveStatus === 'saved' ? 'Answers autosaved' : 'Saving draft...'}
              </span>
            </div>
          </div>

          <div className="flex items-center gap-4">
            <div className={`flex items-center gap-2 px-3 py-1.5 rounded-xl font-mono font-bold text-sm ${
              secondsRemaining < 180 ? 'bg-rose-50 text-rose-700 animate-pulse' : 'bg-indigo-50 text-indigo-700'
            }`}>
              <Clock className="w-4 h-4" />
              <span>{formatTimer(secondsRemaining)}</span>
            </div>

            <button
              onClick={() => setShowEndModal(true)}
              className="px-4 py-2 bg-rose-600 hover:bg-rose-700 text-white font-bold text-xs uppercase rounded-xl transition-all shadow-xs cursor-pointer"
            >
              Finish Exam
            </button>
          </div>
        </div>

        {/* Question Item Card */}
        {currentQ && (
          <div className="bg-white rounded-3xl border border-slate-200 p-6 sm:p-8 space-y-6 shadow-xs">
            <div className="flex items-center justify-between pb-3 border-b border-slate-100">
              <span className="text-xs font-bold text-indigo-700 uppercase tracking-wider">
                Question {currentQuestionIdx + 1} of {activeExam.questions.length}
              </span>
              <span className="text-xs font-mono font-semibold text-slate-400">
                Marks: {currentQ.marks}
              </span>
            </div>

            <p className="text-base font-semibold text-slate-900 leading-relaxed">
              {currentQ.question_text}
            </p>

            {/* 4 Choices */}
            <div className="space-y-3">
              {currentQ.choices.map((choice) => {
                const isSelected = answers[currentQ.id] === choice.id;
                return (
                  <div
                    key={choice.id}
                    onClick={() => handleSelectChoice(currentQ.id, choice.id)}
                    className={`p-4 rounded-2xl border transition-all cursor-pointer flex items-center justify-between ${
                      isSelected
                        ? 'bg-indigo-50 border-indigo-500 text-indigo-900 font-bold shadow-xs'
                        : 'bg-slate-50 border-slate-200 hover:bg-slate-100 text-slate-800'
                    }`}
                  >
                    <span className="text-xs">{choice.text}</span>
                    <div className={`w-5 h-5 rounded-full border flex items-center justify-center ${
                      isSelected ? 'border-indigo-600 bg-indigo-600 text-white' : 'border-slate-300'
                    }`}>
                      {isSelected && <CheckCircle2 className="w-4 h-4" />}
                    </div>
                  </div>
                );
              })}
            </div>

            {/* Navigation & Question Palette */}
            <div className="flex items-center justify-between pt-4 border-t border-slate-100">
              <button
                disabled={currentQuestionIdx === 0}
                onClick={() => setCurrentQuestionIdx((p) => p - 1)}
                className="px-4 py-2 border border-slate-200 rounded-xl text-xs font-bold text-slate-600 disabled:opacity-40"
              >
                Previous
              </button>

              <div className="flex gap-1.5 overflow-x-auto max-w-xs">
                {activeExam.questions.map((q, idx) => (
                  <button
                    key={q.id}
                    onClick={() => setCurrentQuestionIdx(idx)}
                    className={`w-7 h-7 rounded-lg text-xs font-mono font-bold flex items-center justify-center transition-all ${
                      currentQuestionIdx === idx
                        ? 'bg-indigo-600 text-white'
                        : answers[q.id]
                        ? 'bg-emerald-100 text-emerald-800'
                        : 'bg-slate-100 text-slate-500'
                    }`}
                  >
                    {idx + 1}
                  </button>
                ))}
              </div>

              <button
                disabled={currentQuestionIdx === activeExam.questions.length - 1}
                onClick={() => setCurrentQuestionIdx((p) => p + 1)}
                className="px-4 py-2 bg-indigo-600 text-white rounded-xl text-xs font-bold disabled:opacity-40"
              >
                Next
              </button>
            </div>
          </div>
        )}

        {/* End OTP Verification Modal */}
        {showEndModal && (
          <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-xs flex items-center justify-center p-4">
            <div className="bg-white rounded-3xl p-6 sm:p-8 max-w-md w-full space-y-5 border border-slate-200 shadow-2xl">
              <div className="w-12 h-12 rounded-2xl bg-amber-50 text-amber-600 flex items-center justify-center mx-auto">
                <Lock className="w-6 h-6" />
              </div>
              <div className="text-center">
                <h3 className="text-base font-black text-slate-900">Finish & Submit Examination</h3>
                <p className="text-xs text-slate-500 mt-1">
                  You have answered {answeredCount} of {activeExam.questions.length} questions. Enter End OTP from your teacher to finalize.
                </p>
              </div>

              {activeExam.end_otp && (
                <div>
                  <label className="text-[11px] font-bold uppercase text-slate-500 block mb-1">Teacher's End OTP</label>
                  <input
                    type="text"
                    value={enteredEndOtp}
                    onChange={(e) => setEnteredEndOtp(e.target.value)}
                    placeholder="Enter 6-digit End OTP"
                    className="w-full p-3 border border-slate-300 rounded-xl text-center font-mono font-bold text-lg tracking-widest"
                  />
                </div>
              )}

              <div className="grid grid-cols-2 gap-3 pt-2">
                <button
                  type="button"
                  onClick={() => setShowEndModal(false)}
                  className="py-2.5 border border-slate-300 rounded-xl text-xs font-bold text-slate-600"
                >
                  Return to Exam
                </button>
                <button
                  type="button"
                  onClick={handleFinalSubmit}
                  className="py-2.5 bg-emerald-600 hover:bg-emerald-700 text-white font-bold text-xs uppercase rounded-xl shadow-md"
                >
                  Submit Answers
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    );
  }

  // 3. Exam Selection & Start OTP Gate
  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="bg-white p-6 rounded-2xl border border-slate-200 shadow-xs">
        <h2 className="text-xl font-black text-slate-900">Active Online Tests & Examinations</h2>
        <p className="text-xs text-slate-500 mt-1">
          Enter the active Start OTP displayed by your teacher to begin your timed test. Answers are automatically preserved.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
        {exams.map((exam) => (
          <div key={exam.id} className="bg-white rounded-3xl border border-slate-200 p-6 space-y-4 shadow-xs">
            <div className="flex items-center justify-between">
              <span className="text-[10px] font-bold bg-indigo-50 text-indigo-700 px-2.5 py-0.5 rounded-full uppercase">
                {exam.subject} • Class {exam.student_class}-{exam.section}
              </span>
              <span className="text-xs font-mono font-bold text-slate-400">
                {exam.duration_minutes} Mins
              </span>
            </div>

            <div>
              <h3 className="text-base font-bold text-slate-900">{exam.exam_name}</h3>
              <p className="text-xs text-slate-500 mt-1">
                {exam.questions?.length || 0} Multiple Choice Questions • Total {exam.total_marks} Marks
              </p>
            </div>

            <div className="space-y-2 pt-2 border-t border-slate-100">
              <label className="text-[11px] font-bold uppercase text-slate-500 block">
                Enter Teacher's Start OTP (10s Live Code)
              </label>
              <div className="flex gap-2">
                <input
                  type="text"
                  maxLength={6}
                  value={enteredStartOtp}
                  onChange={(e) => setEnteredStartOtp(e.target.value)}
                  placeholder="e.g. 784219"
                  className="w-full p-2.5 bg-slate-50 border border-slate-300 rounded-xl text-center font-mono font-bold text-sm tracking-widest uppercase"
                />
                <button
                  onClick={() => handleStartExam(exam)}
                  className="px-5 bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-xs uppercase rounded-xl transition-all shrink-0 cursor-pointer shadow-xs"
                >
                  Start Test
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
